name: python_CI

on: workflow_call

jobs:

  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Setup python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    - uses: actions/cache@v3
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-pip-${{ hashFiles('test/requirements.txt') }}
        restore-keys: ${{ env.pythonLocation }}-pip
    - name: Check for existence of .github/install.sh
      id: check_install
      uses: andstor/file-existence-action@v2
      with:
        files: ".github/install.sh"
    - name: Run .github/install.sh
      if: steps.check_install.outputs.files_exists == 'true'
      run: |
        ./.github/install.sh
    - name: Install CI requirements
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel
        pip install flake8 bandit pylint pylint-mccabe ochrona pytest pytest-benchmark pytest-sugar
    - name: Check for existence of testing requirements
      id: check_test_reqs
      uses: andstor/file-existence-action@v2
      with:
        files: "test/requirements.txt"
    - name: Install testing requirements
      run: |
        pip install -r test/requirements.txt
      if: steps.check_test_reqs.outputs.files_exists == 'true'
    - name: Check for existence of project requirements
      id: check_reqs
      uses: andstor/file-existence-action@v2
      with:
        files: "requirements.txt"
    - name: Install project requirements
      run: |
        pip install -r requirements.txt
      if: steps.check_reqs.outputs.files_exists == 'true'
    - name: Check for existence of setup.py
      id: check_setup
      uses: andstor/file-existence-action@v2
      with:
        files: "setup.py"
    - name: Run setup.py to install as a package
      if: steps.check_setup.outputs.files_exists == 'true'
      run: |
        python setup.py install
    - name: Flake8
      run: |
        flake8 . --exit-zero --max-complexity=10 --max-line-length=127
      if: always()
    - name: Bandit
      run: bandit . -r --exclude /test
      if: always()
    - name: Ochrona (highlights known package vulnerabilities)
      run: ochrona .
      if: always()
    - name: Analyse the code with pylint
      run: |
        echo $(git ls-files '*.py')
        pylint $(git ls-files '*.py') --fail-under=9
      if: always()
    - name: Run tests
      run: |
        pytest --rootdir=. --color=yes
      if: always()
    - name: Upload /test/output folder artifacts
      uses: actions/upload-artifact@v3
      with:
        name: test_output
        path: "./test/output/"
        if-no-files-found: warn
      if: always()
